platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.0.0-beta.1_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.0.0-beta.1_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/ios'
  pod 'CapacitorActionSheet', :path => '../../node_modules/.pnpm/@capacitor+action-sheet@1.0.8_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/action-sheet'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@4.0.0-beta.0_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/app'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@capacitor+filesystem@4.0.0-beta.0_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/.pnpm/@capacitor+haptics@4.0.0-beta.0_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@4.0.0-beta.0_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/keyboard'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@4.0.0-beta.0_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@4.0.0-beta.0_qfuzndltgxl2urjhs3dhjxydza/node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
